# Shell variables
# Generated by 'wal'
wallpaper='/home/magnus/Wallpapers/Artwork/planetary_excursion.jpg'

# Special
background='#0A1E2B'
foreground='#c7bac3'
cursor='#c7bac3'

# Colors
color0='#0A1E2B'
color1='#5C5B6F'
color2='#9B506D'
color3='#C34266'
color4='#4E708D'
color5='#BF6790'
color6='#528899'
color7='#c7bac3'
color8='#8b8288'
color9='#5C5B6F'
color10='#9B506D'
color11='#C34266'
color12='#4E708D'
color13='#BF6790'
color14='#528899'
color15='#c7bac3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
